GET https://localhost:5131/ordly
###
GET https://localhost:5131/users
###
PUT https://localhost:20396/api/v1/Ordly/guess
content-type: application/json; charset=utf-8

{
  "userId": 0,
  "totalGames": "1",
  "totalWins": "1",
  "currentStreak": "1",
  "longestStreak": "1"
}

###
DELETE https://localhost:5131/user/1

###
POST https://localhost:20396/api/v1/Ordly/guess
content-type: application/json; charset=utf-8

{
  "Guess": "tusse"
}

###